server:
  port: 9001

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false


  datasource:
    url: jdbc:h2:tcp://localhost/~/shopping-mall
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql : true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234
  devtools:
    livereload:
      enabled: true

file:
  path: C:/Users/jwo97/Desktop/shoesmall/src/main/resources/static/upload/

logging.level:
  org.hibernate.type: trace

